Data, information, knowledge and wisdom are closely related concepts, but each has its own role in relation to the other, and each term has its own meaning. According to a common view, data are collected and analyzed; data only becomes information suitable for making decisions once it has been analyzed in some fashion.[8] One can say that the extent to which a set of data is informative to someone depends on the extent to which it is unexpected by that person. The amount of information contained in a data stream may be characterized by its Shannon entropy.

Knowledge is the understanding based on extensive experience dealing with information on a subject. For example, the height of Mount Everest is generally considered data. The height can be measured precisely with an altimeter and entered into a database. This data may be included in a book along with other data on Mount Everest to describe the mountain in a manner useful for those who wish to make a decision about the best method to climb it. An understanding based on experience climbing mountains that could advise persons on the way to reach Mount Everest's peak may be seen as "knowledge". The practical climbing of Mount Everest's peak based on this knowledge may be seen as "wisdom". In other words, wisdom refers to the practical application of a person's knowledge in those circumstances where good may result. Thus wisdom complements and completes the series "data", "information" and "knowledge" of increasingly abstract concepts.

Data are often assumed to be the least abstract concept, information the next least, and knowledge the most abstract.[9] In this view, data becomes information by interpretation; e.g., the height of Mount Everest is generally considered "data", a book on Mount Everest geological characteristics may be considered "information", and a climber's guidebook containing practical information on the best way to reach Mount Everest's peak may be considered "knowledge". "Information" bears a diversity of meanings that ranges from everyday usage to technical use. This view, however, has also been argued to reverse the way in which data emerges from information, and information from knowledge.[10] Generally speaking, the concept of information is closely related to notions of constraint, communication, control, data, form, instruction, knowledge, meaning, mental stimulus, pattern, perception, and representation. Beynon-Davies uses the concept of a sign to differentiate between data and information; data are a series of symbols, while information occurs when the symbols are used to refer to something.[11][12]

Before the development of computing devices and machines, people had to manually collect data and impose patterns on it. Since the development of computing devices and machines, these devices can also collect data. In the 2010s, computers are widely used in many fields to collect data and sort or process it, in disciplines ranging from marketing, analysis of social services usage by citizens to scientific research. These patterns in data are seen as information which can be used to enhance knowledge. These patterns may be interpreted as "truth" (though "truth" can be a subjective concept), and may be authorized as aesthetic and ethical criteria in some disciplines or cultures. Events that leave behind perceivable physical or virtual remains can be traced back through data. Marks are no longer considered data once the link between the mark and observation is broken.[13]

Mechanical computing devices are classified according to the means by which they represent data. An analog computer represents a datum as a voltage, distance, position, or other physical quantity. A digital computer represents a piece of data as a sequence of symbols drawn from a fixed alphabet. The most common digital computers use a binary alphabet, that is, an alphabet of two characters, typically denoted "0" and "1". More familiar representations, such as numbers or letters, are then constructed from the binary alphabet. Some special forms of data are distinguished. A computer program is a collection of data, which can be interpreted as instructions. Most computer languages make a distinction between programs and the other data on which programs operate, but in some languages, notably Lisp and similar languages, programs are essentially indistinguishable from other data. It is also useful to distinguish metadata, that is, a description of other data. A similar yet earlier term for metadata is "ancillary data." The prototypical example of metadata is the library catalog, which is a description of the contents of books.

If you work in human services because you hate math, terms like “data,” “quantitative analysis,” or “pivot table” might sound scary. Don’t be intimidated! Data does not have to be complicated. Simply stated, data is useful information that you collect to support organizational decision-making and strategy.

The list below shares twelve reasons why data is important, what you can do with it, and how it relates to the human services field. You can also download ’12 Reasons Why Data Is Important’ to print out copies and share with your colleagues and other stakeholders.

1. Improve People’s Lives
Data will help you to improve quality of life for people you support: Improving quality is first and foremost among the reasons why organizations should be using data. By allowing you to measure and take action, an effective data system can enable your organization to improve the quality of people’s lives.

2. Make Informed Decisions
Data = Knowledge. Good data provides indisputable evidence, while anecdotal evidence, assumptions, or abstract observation might lead to wasted resources due to taking action based on an incorrect conclusion.

3. Stop Molehills From Turning Into Mountains
Data allows you to monitor the health of important systems in your organization: By utilizing data for quality monitoring, organizations are able to respond to challenges before they become full-blown crisis. Effective quality monitoring will allow your organization to be proactive rather than reactive and will support the organization to maintain best practices over time.

4. Get The Results You Want
Data allows organizations to measure the effectiveness of a given strategy: When strategies are put into place to overcome a challenge, collecting data will allow you to determine how well your solution is performing, and whether or not your approach needs to be tweaked or changed over the long-term.

5. Find Solutions To Problems
Data allows organizations to more effectively determine the cause of problems. Data allows organizations to visualize relationships between what is happening in different locations, departments, and systems. If the number of medication errors has gone up, is there an issue such as staff turnover or vacancy rates that may suggest a cause? Looking at these data points side-by-side allows us to develop more accurate theories, and put into place more effective solutions.

6. Back Up Your Arguments
Data is a key component to systems advocacy. Utilizing data will help present a strong argument for systems change. Whether you are advocating for increased funding from public or private sources, or making the case for changes in regulation, illustrating your argument through the use of data will allow you to demonstrate why changes are needed.

7. Stop The Guessing Game
Data will help you explain (both good and bad) decisions to your stakeholders. Whether or not your strategies and decisions have the outcome you anticipated, you can be confident that you developed your approach based not upon guesses, but good solid data.

8. Be Strategic In Your Approaches
Data increases efficiency. Effective data collection and analysis will allow you to direct scarce resources where they are most needed. If an increase in significant incidents is noted in a particular service area, this data can be dissected further to determine whether the increase is widespread or isolated to a particular site. If the issue is isolated, training, staffing, or other resources can be deployed precisely where they are needed, as opposed to system-wide. Data will also support organizations to determine which areas should take priority over others.

9. Know What You Are Doing Well
Data allows you to replicate areas of strength across your organization. Data analysis will support you to identify high-performing programs, service areas, and people. Once you identify your high-performers, you can study them in order to develop strategies to assist programs, service areas and people that are low-performing.

10. Keep Track Of It All
Good data allows organizations to establish baselines, benchmarks, and goals to keep moving forward. Because data allows you to measure, you will be able to establish baselines, find benchmarks and set performance goals. A baseline is what a certain area looks like before a particular solution is implemented. Benchmarks establish where others are at in a similar demographic, such as Personal Outcome Measures® national data. Collecting data will allow your organization to set goals for performance and celebrate your successes when they are achieved.

11. Make The Most Of Your Money
Funding is increasingly outcome and data-driven. With the shift from funding that is based on services provided to funding that is based on outcomes achieved, it is increasingly important for organizations to implement evidence-based practice and develop systems to collect and analyze data.

12. Access The Resources Around You
Your organization probably already has most of the data and expertise you need to begin analysis. Your HR office probably already tracks data regarding your staff. You are probably already reporting data regarding incidents to your state oversight agency. You probably have at least one person in your organization who has experience with Excel. But, if you don’t do any of these things, there is still hope! There are lots of free resources online that can get you started. Do a web search for “how to analyze data” or “how to make a chart in Excel.”
